### DISCUSSION TITLE
Suggestion: Add Optional Window Sensor to Prevent Blinds Closing When Window is Open

### DISCUSSION THREAD

**Discussion by DzianisFrydliand** [basbruss/adaptive-cover#290] [Ideas]
**First of all, I'd like to express my appreciation for all the work you've done in developing the adaptive-cover component. It's been incredibly useful in managing my roller shades, and I'm grateful for your dedication to this project!**

I wanted to share a situation I've encountered and suggest a possible improvement to the adaptive-cover component.

### Situation:
I have a setup where my roller shades might collide with an open window, potentially causing damage. To prevent this, I’ve created an automation that stops the roller shades from closing if the window is open. Here’s the automation I’m using:

```yaml
automation:
  - id: office_prevent_roller_shutter_from_closing_if_window_is_open
    alias: office_prevent_roller_shutter_from_closing_if_window_is_open
    description: Prevents the roller shutter from closing if the window sensor is open.
    trigger:
      - platform: state
        entity_id: cover.office_roller_shade_driver
        to: "closing"  # Trigger when the roller shutter starts to close
    condition:
      - condition: state
        entity_id: binary_sensor.office_window_bottom_sensor_contact
        state: "on"  # Assuming "on" means the window is open
    action:
      - service: cover.stop_cover
        target:
          entity_id: cover.office_roller_shade_driver
      - service: cover.open_cover
        target:
          entity_id: cover.office_roller_shade_driver
```

The issue I’m encountering is that when the adaptive-cover component attempts to close the shades, the automation will intervene and stop the motor, but the motor still starts and then stops repeatedly. This is not ideal as it could wear down the motor over time and create unnecessary noise.

### Suggestion:
Would it be possible to add an optional window sensor to the adaptive-cover component? This sensor could be used to prevent any attempt to close the blinds if the window is detected as open. It would be an excellent feature to enhance the functionality of the component and could prevent potential damage to blinds in situations like mine.

Thank you again for your hard work, and I hope this suggestion can be considered for a future update!

Best regards,
Dzianis
