### ISSUE TITLE
Ability to define a switch as lux device

### ISSUE THREAD

**Issue by mathiasbl** [basbruss/adaptive-cover#233]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I've been using this amazing integration to control my covers but I want to go the next step to control them based on the lux value instead of weather predictions.
However, I have a light sensor that doesn't output the lux measurement as a value but I must configure the treshholds in the device itself which just outputs on/off based on that.

It would be nice to also have to possibility to configure switches next to sensors as lux device in the integration.

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Additional context

-

**Comment by basbruss** [comment]
That seems like a very niche application. One approach is to use a template sensor to convert that on/off state into actual values.
```yaml
template:
  - sensor:
      - name: Lux Value
        state: >
          {{ iif(is_state('switch.lux','on'),2000,150) }}
        device_class: illumination
        unit_of_measurement: "lx"
```
with the assumption that the high threshold is `2000lx` and `150lx` is considered as low
