### ISSUE TITLE
Q: How to only allow 0% and 100% (and nothing in between)?

### ISSUE THREAD

**Issue by klaptafel** [basbruss/adaptive-cover#379]
I don't like any cover position except for 0% and 100%. Is it possible to skip al mathematics and just close or open the cover when needed?

**Comment by patrickp78** [comment]
Hi,
Let's have a look on [this tutorial](https://community.home-assistant.io/t/adaptive-cover-in-degraded-mode-waiting-for-some-upgrade-i/868605) I made recently…

**Comment by miezie** [comment]
I’d advice to use plain automations then… or a simple blueprint.

**Comment by JokerGermany** [comment]
I had the same requirement and would advice:
Configure adaptive cover and then make an automation and test if sensor.xxx_position is greater 99 or lower than 100.
If higher than 99 open, i lower close.

Something like:
```
if:
  - condition: or
    conditions:
      - condition: template
        value_template: |-
          {% if 'cloud' in states('weather.musterstadt') or 'rainy' in
                                states('weather.musterstadt') or 'pouring' in
                                states('weather.musterstadt') %}
                                    true
                                {% else %}
                                    false
                                {% endif %}
        alias: schlechtes Wetter
      - condition: numeric_state
        entity_id: sensor.vertical_xxx_position
        above: 99
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: -10
        enabled: true
then:
  - action: cover.open_cover
    data: {}
    enabled: true
    target:
      entity_id: cover.rollo_xxx
else:
  - action: cover.close_cover
    data: {}
    enabled: true
    target:
      entity_id: cover.rollo_xxx
```
