### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'attributes'

### ISSUE THREAD

**Issue by FrankTub** [basbruss/adaptive-cover#384]
### What version of Adaptive Cover are you using?

1.4.5

### What version of Home Assistant are you using?

2025.4.3

### Checklist

- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

In the logs I see:

```log
Logger: custom_components.adaptive_cover
Source: helpers/update_coordinator.py:380
integration: Adaptive Cover ([documentation](https://github.com/basbruss/adaptive-cover), [issues](https://github.com/basbruss/adaptive-cover/issues))
First occurred: April 19, 2025 at 7:05:21 PM (23 occurrences)
Last logged: April 20, 2025 at 3:49:08 PM

Unexpected error fetching adaptive_cover data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_cover/coordinator.py", line 298, in _async_update_data
    await self.async_handle_cover_state_change(state)
  File "/config/custom_components/adaptive_cover/coordinator.py", line 356, in async_handle_cover_state_change
    self.manager.handle_state_change(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.state_change_data,
        ^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        self.manual_threshold,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/adaptive_cover/coordinator.py", line 817, in handle_state_change
    new_position = new_state.attributes.get("current_position")
                   ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attributes'
```

And the other behaviour I often see is that some of the sensors of the integration become unavailable. For example:

<img width="569" alt="Image" src="https://github.com/user-attachments/assets/56ba6ca2-2a13-4d72-89b9-69a4e477e6ef" />

And:

<img width="568" alt="Image" src="https://github.com/user-attachments/assets/d731a635-5990-4546-8774-d163623c68dd" />

### Reproduction steps

Not sure why I have this and others don't. Perhaps my device does not have a stable connection? It is regarding my awning that is a Somfy device that is connected via the Homekit device integration. This reverse the state (closed/open) and therefore I created a template cover:

```yaml
- platform: template
  covers:
    reversed_awning:
      friendly_name: "Zonnescherm (Reversed)"
      device_class: awning
      position_template: >
        {% if state_attr('cover.zonnescherm', 'current_position') is not none %}
          {{ 100 - state_attr('cover.zonnescherm', 'current_position') }}
        {% else %}
          0
        {% endif %}
      open_cover:
        action: cover.close_cover
        data:
          entity_id: cover.zonnescherm
      close_cover:
        action: cover.open_cover
        data:
          entity_id: cover.zonnescherm
      set_cover_position:
        action: cover.set_cover_position
        data_template:
          entity_id: cover.zonnescherm
          position: >
            {{ 100 - position }}
```

Not 100% sure if this is the reason why this errors show up, but I guess this is related to it?

### Diagnostics dump

[config_entry-adaptive_cover-01JMVPH72KFYFDZ0ZQR0T6DD0P (1).json](https://github.com/user-attachments/files/19830205/config_entry-adaptive_cover-01JMVPH72KFYFDZ0ZQR0T6DD0P.1.json)
